### PR TITLE
Added constructor L.overpassLayer

### PR DESCRIPTION
**Pull request by pm5**
Making it more like general Leaflet usage (creating objects without `new`.)

### CODE REVIEW

**Comment by GuillaumeAmat** [comment]
Isn't it weird to have two different usages with two distinct spelling? Is it a seen thing?

**Comment by GuillaumeAmat** [comment]
@pm5 ?

**Comment by pm5** [comment]
Sorry, I didn't see the last message.  Leaflet's documentations use lower camel case function calls to create objects, although the same object could be created with the `new` operation on the upper camel case class names.  For example, it [uses](http://leafletjs.com/reference-1.0.2.html#tilelayer):

```
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?{foo}', {foo: 'bar'}).addTo(map);
```

to create `TileLayer` object, which can also be created with `new L.TileLayer(...)`.

So I think people do it both ways.  But what really motivated me to propose the addition was that I'd like to use leaflet-overpass-layer with TypeScript.

The problem is that the popular [type definition for Leaflet](https://www.npmjs.com/package/@types/leaflet) declares these classes as interfaces, and only allows you to create objects with the function call style (because they are not classes anymore.)  Since leaflet-overpass-layer currently only allows object creation with `new` and forbids the function call style, that makes it a bit tricky to supply a type definition for overpass layer.

**Comment by GuillaumeAmat** [comment]
Oh ok, it makes sense!
I'll take care of it, thanks for your pull request :)

**Comment by GuillaumeAmat** [comment]
Done and released as the 2.5.0 version!

**Pull request merged**
